type vector = untyped

module Bezier
  VERSION: String
  RELEASE_DATE: String

  class Point
    extend Forwardable

    attr_reader vector: vector

    def to_a: () -> Array[Float | Integer]
    def to_ary: () -> Array[Float | Integer]
    def size: () -> Integer

    def initialize: (untyped) -> void

    def x: () -> Numeric
    def y: () -> Numeric
    def z: () -> Numeric

    def ==: (Point) -> bool
    def +: (Point) -> Point
    def -: (Point) -> Point
    def *: (Numeric) -> Point

    def interpolate_to: (Point, Float | Integer) -> Point
    def distance_from: (Point) -> Float
    def angle_to: (Point, Point) -> Float

    def magnitude: -> Float

    def zip: (Point) -> Array[Array[Numeric]]
  end
end
